export const environment = {
  production: true,
  ACCESSKEYBUCKET: 'PLACEHOLDER_BUCKET_ACCESS_KEY',
  SECREYKEYBUCKET: 'PLACEHOLDER_BUCKET_SECRET_KEY',
  ACCESSKEYEMAIL: 'PLACEHOLDER_SES_ACCESS_KEY',
  SECRETKEYEMAIL: 'PLACEHOLDER_SES_SECRET_KEY'
};
