export const environment = {
  production: true,
  ACCESSKEYBUCKET: 'AKIA4WBQCFL3FG3SDHOK',
  SECREYKEYBUCKET: 'lagSC4LRPUNKrItluf2ckAsu1XUqHTLbJoqLp15Y',
  ACCESSKEYEMAIL: 'AKIA4WBQCFL3EKN7CKVO',
  SECRETKEYEMAIL: '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'
};
