export const environment = {
  production: false,
  ACCESSKEYBUCKET: 'ACCESSKEYBUCKET',
  SECREYKEYBUCKET: 'SECREYKEYBUCKET',
  ACCESSKEYEMAIL: 'ACCESSKEYEMAIL',
  SECRETKEYEMAIL: 'SECRETKEYEMAIL'
};
